### ISSUE TITLE
リンク切れの箇所がある

### ISSUE THREAD

**Issue by kuone314** [vscodejp/handson-hello-vscode-extension#12]
リンク先へ飛べない箇所が有りました。

* [Top](https://github.com/vscodejp/handson-hello-vscode-extension) の「作成した拡張機能をインストールしよう」
* [スニペットを追加しよう](https://github.com/vscodejp/handson-hello-vscode-extension/blob/main/docs/beginner/03_snippet.md) の「Hello World を作成しよう」

**Comment by Ikuyadeu** [comment]
@kuone314 
ご指摘いただきありがとうございます!
https://github.com/vscodejp/handson-hello-vscode-extension/pull/13 より解決いたしました。
@dafujii ご対応いただきありがとうございます。
