### ISSUE TITLE
Typo: Yaoman

### ISSUE THREAD

**Issue by ftnext** [vscodejp/handson-hello-vscode-extension#14]
素晴らしいハンズオンテキストをありがとうございます。
環境構築から始め、基礎編の「ドキュメントを編集する拡張機能を作る」まで進められました。
さらにそれを改造して「特定の単語の直後に決まったemojiを追加する拡張機能」が手元で動かせています！

環境構築のテキストの中に[Yeoman](https://yeoman.io/)をYaomanとtypoしている箇所があるのに気づきました（2文字目のeをaにtypoしています）。

https://github.com/vscodejp/handson-hello-vscode-extension/blob/bd882275b6802f9c3bcb5717ae0f32cbe2d89a60/docs/00_prepare.md#L8

https://github.com/vscodejp/handson-hello-vscode-extension/blob/bd882275b6802f9c3bcb5717ae0f32cbe2d89a60/docs/00_prepare.md#L28
※一文の中にtypoが2箇所あります

リポジトリの中を検索していますが、修正対象は上記ファイル内の3箇所のみと思われます。

**Comment by Ikuyadeu** [comment]
@ftnext 
資料を読んでいただいただけでなく、typoまで見つけていただきありがとうございます！
該当プルリクエストをマージいたしました。

> さらにそれを改造して「特定の単語の直後に決まったemojiを追加する拡張機能」が手元で動かせています！

すばらしい！今後とも拡張機能開発を楽しんでいただけると幸いです。
